#pragma once

// From glfw3.h
#define BASIL_KEY_SPACE              32
#define BASIL_KEY_APOSTROPHE         39
#define BASIL_KEY_COMMA              44
#define BASIL_KEY_MINUS              45
#define BASIL_KEY_PERIOD             46
#define BASIL_KEY_SLASH              47
#define BASIL_KEY_0                  48
#define BASIL_KEY_1                  49
#define BASIL_KEY_2                  50
#define BASIL_KEY_3                  51
#define BASIL_KEY_4                  52
#define BASIL_KEY_5                  53
#define BASIL_KEY_6                  54
#define BASIL_KEY_7                  55
#define BASIL_KEY_8                  56
#define BASIL_KEY_9                  57
#define BASIL_KEY_SEMICOLON          59
#define BASIL_KEY_EQUAL              61
#define BASIL_KEY_A                  65
#define BASIL_KEY_B                  66
#define BASIL_KEY_C                  67
#define BASIL_KEY_D                  68
#define BASIL_KEY_E                  69
#define BASIL_KEY_F                  70
#define BASIL_KEY_G                  71
#define BASIL_KEY_H                  72
#define BASIL_KEY_I                  73
#define BASIL_KEY_J                  74
#define BASIL_KEY_K                  75
#define BASIL_KEY_L                  76
#define BASIL_KEY_M                  77
#define BASIL_KEY_N                  78
#define BASIL_KEY_O                  79
#define BASIL_KEY_P                  80
#define BASIL_KEY_Q                  81
#define BASIL_KEY_R                  82
#define BASIL_KEY_S                  83
#define BASIL_KEY_T                  84
#define BASIL_KEY_U                  85
#define BASIL_KEY_V                  86
#define BASIL_KEY_W                  87
#define BASIL_KEY_X                  88
#define BASIL_KEY_Y                  89
#define BASIL_KEY_Z                  90
#define BASIL_KEY_LEFT_BRACKET       91
#define BASIL_KEY_BACKSLASH          92
#define BASIL_KEY_RIGHT_BRACKET      93
#define BASIL_KEY_GRAVE_ACCENT       96
#define BASIL_KEY_WORLD_1            161
#define BASIL_KEY_WORLD_2            162

#define BASIL_KEY_ESCAPE             256
#define BASIL_KEY_ENTER              257
#define BASIL_KEY_TAB                258
#define BASIL_KEY_BACKSPACE          259
#define BASIL_KEY_INSERT             260
#define BASIL_KEY_DELETE             261
#define BASIL_KEY_RIGHT              262
#define BASIL_KEY_LEFT               263
#define BASIL_KEY_DOWN               264
#define BASIL_KEY_UP                 265
#define BASIL_KEY_PAGE_UP            266
#define BASIL_KEY_PAGE_DOWN          267
#define BASIL_KEY_HOME               268
#define BASIL_KEY_END                269
#define BASIL_KEY_CAPS_LOCK          280
#define BASIL_KEY_SCROLL_LOCK        281
#define BASIL_KEY_NUM_LOCK           282
#define BASIL_KEY_PRINT_SCREEN       283
#define BASIL_KEY_PAUSE              284
#define BASIL_KEY_F1                 290
#define BASIL_KEY_F2                 291
#define BASIL_KEY_F3                 292
#define BASIL_KEY_F4                 293
#define BASIL_KEY_F5                 294
#define BASIL_KEY_F6                 295
#define BASIL_KEY_F7                 296
#define BASIL_KEY_F8                 297
#define BASIL_KEY_F9                 298
#define BASIL_KEY_F10                299
#define BASIL_KEY_F11                300
#define BASIL_KEY_F12                301
#define BASIL_KEY_F13                302
#define BASIL_KEY_F14                303
#define BASIL_KEY_F15                304
#define BASIL_KEY_F16                305
#define BASIL_KEY_F17                306
#define BASIL_KEY_F18                307
#define BASIL_KEY_F19                308
#define BASIL_KEY_F20                309
#define BASIL_KEY_F21                310
#define BASIL_KEY_F22                311
#define BASIL_KEY_F23                312
#define BASIL_KEY_F24                313
#define BASIL_KEY_F25                314
#define BASIL_KEY_KP_0               320
#define BASIL_KEY_KP_1               321
#define BASIL_KEY_KP_2               322
#define BASIL_KEY_KP_3               323
#define BASIL_KEY_KP_4               324
#define BASIL_KEY_KP_5               325
#define BASIL_KEY_KP_6               326
#define BASIL_KEY_KP_7               327
#define BASIL_KEY_KP_8               328
#define BASIL_KEY_KP_9               329
#define BASIL_KEY_KP_DECIMAL         330
#define BASIL_KEY_KP_DIVIDE          331
#define BASIL_KEY_KP_MULTIPLY        332
#define BASIL_KEY_KP_SUBTRACT        333
#define BASIL_KEY_KP_ADD             334
#define BASIL_KEY_KP_ENTER           335
#define BASIL_KEY_KP_EQUAL           336
#define BASIL_KEY_LEFT_SHIFT         340
#define BASIL_KEY_LEFT_CONTROL       341
#define BASIL_KEY_LEFT_ALT           342
#define BASIL_KEY_LEFT_SUPER         343
#define BASIL_KEY_RIGHT_SHIFT        344
#define BASIL_KEY_RIGHT_CONTROL      345
#define BASIL_KEY_RIGHT_ALT          346
#define BASIL_KEY_RIGHT_SUPER        347
#define BASIL_KEY_MENU               348